### ISSUE TITLE
Put the most popular languages at the top of the list

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#10]
We should sort like the top 5 languages at the top of the language chooser. It would save time for the majority of our users. Maybe throw them up there in order of popularity then a separator then everything else in alphabetical order.

**Comment by lewisgoddard** [comment]
The only part I disagree with is the everything else, I quite often scroll through the list, only to find English is _only_ at the very top, totally out of order.

**Comment by danrabbit** [comment]
Yeah that's a valid point. Should be both. Or maybe we should exclude those type items from the scroll?

**Comment by lewisgoddard** [comment]
Depends on how high that section ends up being. 5 items seems like a little much, but three? Maybe not.

Country | Percentage
---|---
en | 42.81%
es | 13.66%
ru | 6.49%
de | 5.42%
pt_BR | 6.21%
it | 4.50%
zh_CN | 2.73%
fr | 2.79%
pl | 2.07%
nl | 1.30%
