### ISSUE TITLE
Put language locales in a stack (like keyboard layout selection)

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#11]
Would probably cut down the size of the list and make it easier to access languages. For example if we're sorting English to top now that's US, GB, Australian, Canadian, etc all at the top but compact.

**Comment by cassidyjames** [comment]
@danrabbit is this still relevant with the new design? Would we do the stack like we do for keyboard layouts?

**Comment by danrabbit** [comment]
Closed in #182
