### ISSUE TITLE
More advanced partitioning

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#153]
Right now we're working toward an mvp where you just select a disk to blow away, but we obviously want to figure out a solution for more advanced/complicated partitioning schemes.

**Comment by cassidyjames** [comment]
The more we talk about and work through this, the more I'm in favor of just passing this off to an embedded blivet widget or something.

**Comment by danrabbit** [comment]
It sounds like we have two main sections: Magic Partitioning and Muggle Partitioning.

For Magic Partitioning

We want to provide simple options for common partitioning problems like clean disks, disks with an old OS, disks with an updated OS, disks with some other OS, disks with multiple OSes etc. Here we should have an easy way to deal with resizing partitions for multi-boot setups

For Muggle Partitioning

We only want to handle selecting what to do with each partition, like use as root, use as home, etc. We'll defer to an external tool for actually changing the size and format of these partitions.

**Comment by danrabbit** [comment]
After some frantic whiteboarding, we decided we need two new functions in distinst. We need to know what is on a partition (so we can detect whether to prompt upgrade/refresh or dual boot) and we need to know what distinst can do with a partition (for the custom screen)

**Comment by cassidyjames** [comment]
Advanced (Muggle) partitioning is currently merged into master. Right now we're building the CustomPartitioning view with storage-bar inspired widgets that let you pick the partitions to use, and a button to pop open GParted. I'm closing this issue since that's what we initially were talking about with this issue, and we can open an issue for "Magic Partitioning"
