### ISSUE TITLE
Installer should inhibit sleep

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#16]
While open, the installer should inhibit sleep

**Comment by cassidyjames** [comment]
@Philip-Scott wrote an inhibitor class as part of Videos that could be relevant: https://github.com/elementary/videos/blob/master/src/Services/Inhibitor.vala

**Comment by Philip-Scott** [comment]
Import it and `Inhibitor.get_instance ().inhibit ()` :tada:
