### ISSUE TITLE
Explain that demo mode isn't optimal

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#202]
We should add some kind of copy to explain that while in demo mode performance may be impacted and some features may not be available (notably AppCenter)

**Comment by PMiner** [comment]
demo mode being, booting from the live installation?

**Comment by btkostner** [comment]
@PMiner yes

**Comment by PMiner** [comment]
like a notification, a pop-up window, a little text in the corner? something like that?

**Comment by lainsce** [comment]
Maybe add some floating text on top of the wallpaper in the bottom right or left with "Demo Mode - Some things might not work correctly" as maybe the copy?

**Comment by SubhadeepJasu** [comment]
Having a sticky banner to the bottom corner which says "Demo mode isn't optimal" with two buttons "More Info" and "Install". Just an idea.

**Comment by PiFi** [comment]
Maybe a sticky notification would fit with the OS theme better?

**Comment by cassidyjames** [comment]
To clarify, the scope here is just within the Installer UI itself, not during the live session.

**Comment by PiFi** [comment]
Yes

**Comment by cassidyjames** [comment]
Would adding a fourth item in the row make sense, or do we start to run out of room?

i.e. from:

![elementary-try-or-install](https://user-images.githubusercontent.com/611168/33397880-4dc851de-d50a-11e7-9e7d-91ed48f05eb3.png)

to:

># Install elementary OS
>You can install elementary OS on this device now, or try Demo Mode without installing.
>
>:white_check_mark: | :arrow_left: | :arrow_down: | :no_entry_sign: 
>--- | --- | --- | ---
>Data from your previous operating system is unchanged in Demo Mode | Any changes you make in Demo Mode will not be saved | You can always return to the installer from Demo Mode by selecting the Install icon. | Performance and features in Demo Mode may not reflect the installed experience.

(terrible markdown mockup aside)

**Comment by PiFi** [comment]
I think four might fit if you put them in a 2x2 grid

**Comment by PiFi** [comment]
But that might look strange.

**Comment by lainsce** [comment]
Maybe move the fourth item below the demo mode one, as a new paragraph, with a red icon to catch attention?

**Comment by PiFi** [comment]
![33397880-4dc851de-d50a-11e7-9e7d-91ed48f05eb3](https://user-images.githubusercontent.com/20211219/33404006-4062385c-d528-11e7-8964-47a3e8451e64.png)

**Comment by PiFi** [comment]
like this?

**Comment by lainsce** [comment]
@PiFi Actually in the same "column" as the Demo Mode item. :P

**Comment by PiFi** [comment]
?

**Comment by lainsce** [comment]
@PiFi Align your ":no_entry_sign:  <text_here>" with the Demo mode item above, not letting it spill to the other items in the sides. :+1:

**Comment by PiFi** [comment]
the demo mode item being the "Try demo mode" button?

**Comment by lainsce** [comment]
No, the "Any changes you make in Demo Mode..." item ;)

**Comment by PiFi** [comment]
oh ok
