### ISSUE TITLE
Screen dimming for OLED (with solution)

### ISSUE THREAD

**Issue by ZyberSE** [elementary/installer#203]
The built-in dimming function don't work on OLED screens, they handle it slightly different.

This works for OLED and should somehow be implemented into Elementary.

xrandr --output eDP1 --brightness 0   # fully dimmed
xrandr --output eDP1 --brightness 0.5   # half dimmed
xrandr --output eDP1 --brightness 1   # no dimming

**Comment by PMiner** [comment]
how does this affect the installer?

**Comment by ZyberSE** [comment]
Sorry if I posted it in the wrong place, can you direct me where it should go so I can post it there instead?

**Comment by PMiner** [comment]
probably on elementary/wingpanel since there isn't one for the brightness widget that I could find.

**Comment by btkostner** [comment]
I would actually recommend putting an issue on this repo as it's where most screen dimming issues end up: https://github.com/elementary/switchboard-plug-power

**Comment by PMiner** [comment]
oh, I didn't realize that was the power widget! you might also want to put it in elementary/wingpanel-indicator-power as well then.

**Comment by ZyberSE** [comment]
Done, this thread can be removed now.
