### ISSUE TITLE
Time stuck in 24h mode after installing from OEM (loki 0.4.1)

### ISSUE THREAD

**Issue by giovannicaligaris** [elementary/installer#204]
I noticed a very annoying bug after completing a fresh OEM installation. After booting and setting up a user profile from the oem-config, it seems that some of the date and time packages are getting removed.

Wingpanel, tzdata, libboost-date-time1.58.0 and python3-dateutil were removed from the original installation.

Now the time won't switch from 24h to 12h. I even tried to change the settings in dconf but had no success.

What am I missing?

If I do a normal installation, everything works fine.

![vngfp](https://user-images.githubusercontent.com/26255347/32909026-51b8d2f8-cafd-11e7-8c15-16a9ae88f4f2.jpg)

**Comment by giovannicaligaris** [comment]
Dismiss saying that Wingpanel, tzdata, libboost-date-time1.58.0 and python3-dateutil were not installed.

I have tried **sudo dpkg-reconfigure tzdata** but still not success.

**Comment by giovannicaligaris** [comment]
Solved it.

Had to install wingpanel-indicator-datetime_2.0.2+r223+pkg11~daily from the daily ppa.

[](https://launchpad.net/~elementary-os/+archive/ubuntu/daily/+sourcepub/8449080/+listing-archive-extra
)
Everything works now

**Comment by danrabbit** [comment]
Closing as "Invalid" for the installer. The code in this repo is not in production in any case, but this seems to be an issue that was fixed in indicator datetime master
