### ISSUE TITLE
distinst crashes immediately without hardcoding enough_space = true

### ISSUE THREAD

**Issue by codygarver** [elementary/installer#209]
I can't install on my machine, possibly because there's a 4MB partition on the disk. Even though there are other disks/partitions with plenty of space.

**Comment by cassidyjames** [comment]
Wait, is the issue that the disk issue detection is checking if _any too-small_ disks exist instead of checking that _no large-enough_ disks exist? That logic just sounds backwards. :P

**Comment by cassidyjames** [comment]
@codygarver can you expand on this? Is it an issue with the IssueDetect view where it's saying you don't have enough space? Or was it something else?

**Comment by cassidyjames** [comment]
@codygarver provided some more info about this. It sounds like the CheckView logic is just backwards and failing because of small partitions. This check should be rewritten to use distinst, which will solve the issue.

**Comment by codygarver** [comment]
Originally issue persists, hardcoding `enough_space = false` avoids a crash.

**Comment by codygarver** [comment]
```
$ sudo target/debug/examples/list
list: failed: unable to get serial model of device: no serial field
```
but
```
sudo ./examples/vala/list
Segmentation fault
```

**Comment by davidmhewitt** [comment]
I'm going to close this as I'm pretty sure this isn't a thing anymore.

We use distinst to enumerate over the disks, and `enough_space` is set to true if at least one of them has enough space.
