### ISSUE TITLE
oem-install not installing oem-config packages by default

### ISSUE THREAD

**Issue by cheat117** [elementary/installer#210]
Hey all,

In installing Loki Desktop with OEM mode, there is no Ubuntu-like config which allows for an OEM install. This is handy for when you are re-selling a computer or gifting a computer to a friend but you want to prep the system for them (without giving them a password and complicated password-changing steps).

Upon further investigation, oem-config-prepare was not found after the initial install, update and configuration. I had to manually install oem-configure-prepare.

**Comment by danrabbit** [comment]
Hey there! This issue tracker is for a new installer that is not yet being used in production. What you're probably looking for is the tracker for [Ubiquity](https://bugs.launchpad.net/ubuntu/+source/ubiquity), which is the installer shipped in elementary OS today.
