### ISSUE TITLE
ZFS root support

### ISSUE THREAD

**Issue by globalcitizen** [elementary/installer#211]
## Requirements
- Must support installing to existing ZFS pools.
- Manual terminal use as part of the install is fine, it just needs to work (install, boot) and be documented.
  - Boot will require ZFS modules inside the post-install initramfs.

## Notes
 - Future ZFS + LUKS support would be awesome, I will pay for that too (similar amount) if ZFS works out well and is maintained. Therefore, please keep in mind you may need to add LUKS later. LUKS will apparently require prompting for passwords during bootup.

**Comment by globalcitizen** [comment]
Unimpressed at charged download. Withdrawing bounty.

**Comment by cassidyjames** [comment]
@globalcitizen this would be implemented in [pop-os/distinst](https://github.com/pop-os/distinst), not the installer front-end.

Drive encryption is being worked on separately, see #214
