### ISSUE TITLE
Missing content in dialog window?

### ISSUE THREAD

**Issue by orschiro** [elementary/installer#212]
Just installed eOS from `elementaryos-0.4.1-stable.20170814.iso`. 

Something missing in this window? Above copying files it looks very empty.

![image](https://user-images.githubusercontent.com/170947/35341944-25a1660c-0127-11e8-8bb6-56a7e9af2e1e.png)

**Comment by btkostner** [comment]
Those slides where removed on purpose.

Also, that is the old ubiquidy installer. This repository is for a new elementary like installer that is not released yet.

**Comment by cassidyjames** [comment]
@orschiro @btkostner they weren't "removed" so much as nobody made slides for elementary OS. We had a more minimal window there before that blended in, but something in Ubiquity changed and made it stand out more.

**Comment by orschiro** [comment]
@cassidyjames thanks. Anyway it's the old installer... :-)
