### ISSUE TITLE
Feature Selection Menu

### ISSUE THREAD

**Issue by Mikerr1111** [elementary/installer#225]
I was thinking it would be useful to have a 'Feature Selection' menu with a few key apps that would enable the user to select additional applications that would be installed during the installation process. I provided a screenshot example of what Antergos does with their distro. I feel this would be helpful to both a beginner and advanced users who need a minimal setup but also have the opportunity of installing key workflow apps so once the installation process is complete. The user can get straight to work without having to go the app store to get basic apps like LibreOffice and Firefox. 

![feature selection](https://user-images.githubusercontent.com/18353476/36006899-7bd789ce-0cf4-11e8-8015-99e6e494bf07.jpg)

**Comment by cassidyjames** [comment]
The OS installer is not the place for installing apps; its purpose, [as stated in the wiki](https://github.com/elementary/installer/wiki), is to get the OS onto the device and little else.
