### ISSUE TITLE
Installation progress percentage either 0% or 100%

### ISSUE THREAD

**Issue by brs17** [elementary/installer#226]
During the installation process, when progress such as "Configuring the System"(but is true for all of the statuses) is shown it is either listed as 0% complete or 100% complete. 

More granular progress should be shown.

**Comment by brs17** [comment]
When the installer is run from the terminal: `pkexec io.elementary.installer` the percentages update appropriately.

**Comment by jackpot51** [comment]
@mmstick This may be because both stdout and stderr need to be piped when running squashfs

**Comment by cassidyjames** [comment]
This was fixed, yeah?
