### ISSUE TITLE
Terminal output scroll

### ISSUE THREAD

**Issue by brs17** [elementary/installer#227]
Current experience:
When opening the terminal output during the installation, the window always shows the top/beginning of the output. Manual scrolling is required to see the latest progress of the installation.

Expected experience:
When selecting the terminal button, the output should automatically scroll to the bottom to show the most recent output. Whenever this screen is scrolled all the way down, it should continue to scroll when new input is added. If the user scrolls up, automatic scrolling should stop.

**Comment by mmstick** [comment]
Very close to solving this.
