### ISSUE TITLE
"Cancel Installation" button should go back to "Install or Try" screen

### ISSUE THREAD

**Issue by brs17** [elementary/installer#252]
On the drive selection screen, the option to "Cancel Installation" currently only goes back one screen to the last disk encryption page.

This button should probably take the user back to the "Install or Try" screen towards the beginning of the installer (before making decisions about encryption).

It therefore may also make sense then to include a "Back" button to just go back one step to the encryption page(s).

**Comment by cassidyjames** [comment]
Yeah I agree that "Cancel" should go to Try/Install. I think this was just a shortcut for the back button before since Try/Install used to be the previous screen (before we added Encryption).
