### ISSUE TITLE
Live USB Cleared BIOS Boot Sequence on Restart

### ISSUE THREAD

**Issue by dolorsitatem** [elementary/installer#254]
I created a Live USB version of Elementary to preview.  While exploring, I did nothing of consequence. I clicked this icon, searched for that application.  I did not adjust any settings anywhere.  After a superficial survey of the environment, I pressed the power icon and then selected "Restart".  I was next presented with the Elementary logo and a prompt telling me to remove the Live USB and press Enter.  I did this.  When the computer restarted, it booted into a firmware disk check.  On completion, my OS did not load.  I entered the BIOS.  My entire boot sequence had been cleared.  I re-entered in GRUB (as I am a Debian user) and everything is fine and dandy again.  Please let know if there is any more information I can provide you.

**Comment by cassidyjames** [comment]
@dolorsitatem where did you get your ISO? This repository is for the unreleased upcoming installer, and is not currently provided by any public ISOs. See the README:

>Note: this is the work-in-progress installer and has not been released yet. For the current installer, see [Ubiquity](https://wiki.ubuntu.com/Ubiquity).

**Comment by cassidyjames** [comment]
Closing as this is not applicable to the installer repo since this is not shipping; it sounds like a bug with Ubiquity.
