### ISSUE TITLE
installer doesnt work? - why?

### ISSUE THREAD

**Issue by tojestzart** [elementary/installer#276]
after choosing , no i dont want wifi for now pressing continue - nothings happen
> sudo gparted
> 
> (gpartedbin:11839): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
> 
> (gpartedbin:11839): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
> 
> (gpartedbin:11839): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
> 
> (gpartedbin:11839): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
> ======================
> libparted : 3.2
> ======================
> Backtrace has 15 calls on stack:
>   15: /lib/x86_64-linux-gnu/libparted.so.2(ped_assert+0x44) [0x7f19c9e7de94]
>   14: /lib/x86_64-linux-gnu/libparted.so.2(+0x1e4bf) [0x7f19c9e914bf]
>   13: /lib/x86_64-linux-gnu/libparted.so.2(+0xf8ba) [0x7f19c9e828ba]
>   12: /lib/x86_64-linux-gnu/libparted.so.2(ped_disk_add_partition+0x25f) [0x7f19c9e831af]
>   11: /lib/x86_64-linux-gnu/libparted.so.2(+0x1ddaf) [0x7f19c9e90daf]
>   10: /lib/x86_64-linux-gnu/libparted.so.2(+0x1de40) [0x7f19c9e90e40]
>   9: /lib/x86_64-linux-gnu/libparted.so.2(+0x1dde9) [0x7f19c9e90de9]
>   8: /lib/x86_64-linux-gnu/libparted.so.2(+0x1edd5) [0x7f19c9e91dd5]
>   7: /lib/x86_64-linux-gnu/libparted.so.2(ped_disk_new+0x48) [0x7f19c9e82dd8]
>   6: /usr/sbin/gpartedbin() [0x466c0e]
>   5: /usr/sbin/gpartedbin() [0x47555e]
>   4: /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1(+0x4e67d) [0x7f19cb38e67d]
>   3: /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x70bb5) [0x7f19ca346bb5]
>   2: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f19c91b76ba]
>   1: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f19c8eed41d]
> Assertion (metadata_length > 0) at ../../../libparted/labels/dos.c:2313 in function add_logical_part_metadata() failed.
> Aborted (core dumped)
> elementary@elementary:~$ 
>

**Comment by tintou** [comment]
You're talking about the old installer "Ubiquity" that is provided by Ubuntu and tracks issues here: https://launchpad.net/ubiquity

**Comment by tojestzart** [comment]
problem is its related to elementary os since i though its out of the box
