### ISSUE TITLE
Keyboard progression after drive encryption

### ISSUE THREAD

**Issue by brs17** [elementary/installer#280]
**Current Behavior**
After typing in and confirming a password for drive encryption, <kbd>Enter</kbd> does not do anything. Furthermore pressing <kbd>Tab</kbd> first highlights the `Don't Encrypt` button.

**Expected behavior**
After typing in and confirming a password for drive encryption, <kbd>Enter</kbd> should progress the installer to the drive selection page. Pressing <kbd>Tab</kbd> should highlight the `Select Drive` button (especially since <kbd>Enter</kbd> does not work)

**Comment by danrabbit** [comment]
This is resolved in master
