### ISSUE TITLE
`Connect to power` screen transitions the wrong way

### ISSUE THREAD

**Issue by brs17** [elementary/installer#281]
After being provided the warning that the machine should be plugged in before continuing the installation, selecting `Ignore` will transition seemingly backwards(left to right) to the `Drive Encryption` page.

This is the same way selecting `Cancel installation` transitions, the opposite of moving forward in the installation process.

**Comment by cassidyjames** [comment]
I took a brief look at this. It looks like we're adding a whole new stack to the content area, instead of using the one that already exists and transitioning to/from a child.

**Comment by danirabbit** [comment]
This should be fixed now that we use an infobar instead of screen #648
