### ISSUE TITLE
Could Not Install page: broken `Try Demo Mode` button

### ISSUE THREAD

**Issue by brs17** [elementary/installer#283]
When there is an error with the installation and the user is brought to the `Could Not Install` page, the `Try Demo Mode` button does not work.

**Comment by cassidyjames** [comment]
This is because in Pop!_OS, LightDM doesn't exist (so the DBus call doesn't work). Can we be more intelligent in the installer and only show the button if LightDM is there?

**Comment by brs17** [comment]
My concern downstream if the installer is in a full live session, the user then does not have a super straight forward way to close out of the installer (no close button or <kbd>:x: </kbd>). The only option the user has is the dropdown `Quit` in the Gnome shell. 

Perhaps if the installer is in a full live session, that button should just close the window?
