### ISSUE TITLE
Move side-by-side labels to the right half

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#291]
This solves some awkward views like the CheckView and the proposed SuccessView. It'll work well in the downstream as well.

**Comment by cassidyjames** [comment]
@danrabbit noted that if we do this, we'll need bigger icons on the left to balance it out. But @isantop mentioned it still feels a little awkward, even with the big Pop! artwork on the left.

So I think we're still a little undecided on this.

**Comment by danirabbit** [comment]
I think CheckView looked significantly different when this was filed. I wouldn't say it looks awkward these days 

![Screenshot from 2024-09-11 15 03 49](https://github.com/user-attachments/assets/8c5d39c2-c48d-4a74-9e00-ad63604d74fc)

Closing because I think it looks okay now :shrug:
