### ISSUE TITLE
Move encrpytion after disks

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#295]
After a day-long discussion across both the Pop!_Chat and elementary Slack, we've decided to go with this compromise for the Disks and Encryption views:

1. Move Encryption to after disks. This lets us choose a disk to blow away **or** custom partitioning.
2. If the user chooses custom partitioning, we let them do any encryption within that view (since there are some combinations that might not make sense for encryption, or some combinations with more than one encrypted drive and password). We skip the normal Encrypt view in this case.
3. Keep the destructive actions on the disk (and custom) view. This is still considered the point-of-no-return for the installer, even if we don't start writing to disk right now.
4. Remove the back/cancel buttons from the Encrypt view. We don't let them go back, because we consider the installation started at this point.

This way we keep a few considerations from the previous version:

1. Clear association between the non-reversible destructive action and the drive or partitions being "destroyed." We leave this decision and destructive action on the disk view.
2. Consistent placement of the non-reversible destructive action, whether or not the user is encrypting. We always show it on the last drive-related screen, whether that's the blow-away-a-disk screen, the custom screen, or—in the future—a smarter dual boot screen.
3. We still require explicit user action _outside of the button area_ to continue; the destructive button is disabled until you explicitly choose a drive to blow away (or partitions to reuse), so you can never just click through and start the installation without an extra precaution.

I think we're in agreement here and want to try this out. It does mean a teeny tiny fib (the installation is not actually starting until after the encrypt view), but I think the trade-offs are worth it.

**Comment by brs17** [comment]
Thank you for writing this all out (and summing up today's discussion)!
