### ISSUE TITLE
Consider Anaconda as installation backend

### ISSUE THREAD

**Issue by tintou** [elementary/installer#30]
Let's investigate if it's a viable solution

**Comment by jkonecny12** [comment]
We are working on mid to long term project to make Anaconda modular -  which should really help for this (eq. third party UI modules). It will be a long run to implement it so it is not usable right now.

You could use a workaround now in a way with kickstart text installation running as a separate process and parse output of anaconda and logs.

I'll leave this issue open and we will post a comment here about implemented features from the modularisation project which could be helpful for you.

**Comment by danrabbit** [comment]
Closing since we're working with System76 on an installer backend library
