### ISSUE TITLE
Don't install GRUB on EFI install

### ISSUE THREAD

**Issue by tintou** [elementary/installer#31]
EFIs have a dedicated way to chose the OS

**Comment by rgiyf** [comment]
or could you make an option to choose whether to install **grub** or not (e.g _ubiquity -b_)

**Comment by isantop** [comment]
Even with the dedicated EFI stub loader, GRUB is useful to manage kernel updates automatically. Unless elementary ships something like [kernelstub](https://launchpad.net/kernelstub) to handle that sort of thing automatically.

**Comment by danrabbit** [comment]
Gonna close this since this is up to the backend and this repo only covers the frontend
