### ISSUE TITLE
Don't use the word "LUKS"

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#319]
From Google+:

![screenshot from 2018-04-23 14 06 32 2x](https://user-images.githubusercontent.com/7277719/39153325-9c9fe936-46ff-11e8-95f3-24c9be7d51cb.png)

We probably shouldn't expect users to know what LUKS is

**Comment by cassidyjames** [comment]
I was gonna say "well if they're using advanced partitioning on their LUKS drive, they do know what it means" but then I remembered we encrypting by default and never mention LUKS there. :smile: Good call.
