### ISSUE TITLE
Warn about VMs

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#323]
Stolen from deepin. They throw a warning screen if you’re installing on a VM about performance etc. Probably a good idea

**Comment by jwinnie** [comment]
@danrabbit But don’t VM users already understand the issues involved?

**Comment by Philip-Scott** [comment]
Honestly it doesn't hurt to remind them. I'd even go as far as showing a first boot dialog or something due to the amount of people and reviewers that reported bugs based on issues from running it on a VM

**Comment by danrabbit** [comment]
@jwinnie I would say no, nearly never. Very regularly you'll see videos on YouTube where people don't understand that the issues they're encountering are due to having no hardware acceleration, etc

**Comment by jwinnie** [comment]
Okay, I agree. I, too, tried running elementary inside of a VM and I failed.

Maybe like this:

### You are running elementary inside of a virtual machine.
elementary is not designed to be run this way, and you may encounter issues.

**Comment by SubhadeepJasu** [comment]
Its been a regular trend among youtubers to review OSs on VMs and complain about problems that would other wise not occur in a regular installation. Most performance related issues. I have used this OS both on VM and on my main laptop, and the difference is huge.
