### ISSUE TITLE
Desktop mode

### ISSUE THREAD

**Issue by jwinnie** [elementary/installer#324]
The installer should have a “desktop mode” so users can adjust partitions after installing elementaryOS.

**Comment by btkostner** [comment]
How is this different from the normal live mode most Linux distributions have?

**Comment by cassidyjames** [comment]
I think this would effectively mean adding a Demo Mode button to the success screen? What's the use case of changing partitions after installing instead of before?

**Comment by jwinnie** [comment]
@cassidyjames For example, you might run out of space on one partition and need to enlarge it. Maybe you want to wipe another partition. Maybe you installed elementary as dual-boot, then realized it was so great you wanted to remove your original OS. Many cases exist, and it doesn’t hurt to provide the functionality.

Also, it is nice to know how the disk is laid out. It gives the user more control over their computer and increases transparency.

**Comment by jwinnie** [comment]
Maybe something like this:

Hard Drive Layout
|——elementary—|—-Ubuntu——|
[Reboot into Recovery Mode]

**Comment by jwinnie** [comment]
I envision it as a switchboard plug.

**Comment by cassidyjames** [comment]
Interesting thoughts! So if I'm understanding correctly, you're asking for disk-related management in Switchboard?

I'm going to close this issue as it's out of scope for the installer itself, but feel free to open on on the `switchboard` repository, where it can be properly triaged and targeted. I think that would end up being a new plug altogether.
