### ISSUE TITLE
Swapfiles instead of swap partitions

### ISSUE THREAD

**Issue by png2378** [elementary/installer#33]
By default Ubuntu [will be use swapfiles](http://blog.surgut.co.uk/2016/12/swapfiles-by-default-in-ubuntu.html) instead of creating traditional swap partitions. It will no more than 5% of free disk space or 2GiB, whichever is lower. Apparently it's a good idea.

**Comment by cassidyjames** [comment]
This is probably just handled by the back-end; I'm not sure there's any UI work here.

**Comment by danrabbit** [comment]
Closing for the above reason
