### ISSUE TITLE
Recommend storing encryption password somewhere safe

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#353]
Since data is unrecoverable without the encryption password, we should recommend the user stores it somewhere safe. We just want to be careful not to tell them, "write it down and stick it on a note on your monitor".

**Comment by 4jNsY6fCVqZv** [comment]
Would the recommendation to use a secure open source password manager for this purpose be a good idea?

**Comment by isantop** [comment]
That might lead people to set a password which is hard to remember (because they expect it to auto-fill the password) and which is hard to gain access to to recover (since the computer is not yet booted to be able to access the password manager for reference.

**Comment by cassidyjames** [comment]
My thought is we could just mention "write it somewhere safe" on the third bullet about requiring it every reboot.

![image](https://user-images.githubusercontent.com/611168/75478293-ef9a0a80-595a-11ea-9884-56162ef24353.png)

Alternately, we could include it in the sort of warning/disclaimer on the next screen (but I don't like how long that text is getting):

![image](https://user-images.githubusercontent.com/611168/75478599-7c44c880-595b-11ea-8652-3ce14b95c7ce.png)

**Comment by danrabbit** [comment]
I think my gut reaction is that bolding certain parts means our copy is too long. Maybe something like:

:shield: Data will be protected from others with physical access to this device
:stopwatch: Read and write speeds may be minimally impacted during intense tasks
:arrows_counterclockwise: The encryption password will be required each time this device is turned on. Store it somewhere safe.

**Comment by 4jNsY6fCVqZv** [comment]
Is it important to note that the password for hard disk encryption should not be the same as the password for the user account?

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv that is already the case on the next screen.
