### ISSUE TITLE
Use org.gnome.SessionManager.EndSessionDialog

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#354]
We should use this DBus interface instead of shipping our own dialog.

**Comment by cassidyjames** [comment]
I just realized we're not currently running the panel in the installer session, so this might not make sense here. But in Pop!_OS, they are running the installer under a GNOME Shell session, so they do have the interface. We might want to use the interface if it exists and fallback to a built-in dialog otherwise.

**Comment by danrabbit** [comment]
We could also run the panel in greeter mode (`wingpanel -g`) during the installer session

**Comment by cassidyjames** [comment]
@danrabbit oh duh, yeah that could work. One thing we'll have to be aware of is that this will make it easier for people to shut down from the UI when they shouldn't, though. I'm not sure what we should do about that.
