### ISSUE TITLE
[Clarification] If "Install third-party software" is unchecked does Elementary Install Any non-FLOSS Software?

### ISSUE THREAD

**Issue by Nic-Wow1** [elementary/installer#357]
When installing Elementary you will see this:
![virtualbox_elementaryscreenchot_14_10_2018_12_37_52](https://user-images.githubusercontent.com/43324658/46921301-3945b780-cfe9-11e8-9692-5fd7f0b0ed12.png)

As long as "Install third-party software for graphics and Wi-Fi hardware, Flash, MP3 and other media" is unchecked will ElementaryOS install any non-[Libre](https://www.gnu.org/philosophy/floss-and-foss.html) Software?

**Comment by Conan-Kudo** [comment]
If you're going by GNU's definition, then yes, elementary OS will, as it installs firmware for supporting your hardware, and elementary OS does not ship a de-blobbed Linux kernel.

**Comment by Conan-Kudo** [comment]
Well, it depends on what you're scoping for. The "third-party software" checkmark is for proprietary codec packs and such, it's not really for blocking hardware enablement.

**Comment by Nic-Wow1** [comment]
@Conan-Kudo  I don't believe I understand. It appears like you are saying that their may be software pre-installed that is proprietary. I meant software that ElementaryOS adds. Will ElementaryOS install non-FLOSS software?

**Comment by Conan-Kudo** [comment]
To put it simply, elementary OS installs _exactly_ the same way that Ubuntu does, as the installer and installation process is _identical_.

**Comment by cassidyjames** [comment]
Issues are not a discussion platform. Please direct support questions to [StackExchange](https://elementaryos.stackexchange.com) or general discussion to one of the social platforms linked at the top-right of [elementary.io](https://elementary.io).
