### ISSUE TITLE
installer keeps crashing on grub install

### ISSUE THREAD

**Issue by THN1** [elementary/installer#359]
Hi team
the eOS 5.0 installer keeps crashing reproducibly (3 trials) on the grub install /dev/sda (or sdaN) step on my multiboot system (N=8). The resulting partial install is unbootable and unusable.
THN1

**Comment by cassidyjames** [comment]
This issue was moved to elementary/os#143

**Comment by cassidyjames** [comment]
This repo is for a new installer which is not being used in elementary OS yet.
