### ISSUE TITLE
Installer don't show the pictures when installing the system

### ISSUE THREAD

**Issue by pyroxar** [elementary/installer#372]
![IMG_20190421_005620](https://user-images.githubusercontent.com/23406555/56463280-3335f680-63d1-11e9-99e3-78d98425bdfa.jpg)

**Comment by cassidyjames** [comment]
This repo is for the new installer that is not yet shipping with elementary OS. The new installer does not have a screen like this. Consequently, I'm closing this as out of scope.

Further, there are no images to be shown in the Ubiquity installer.
