### ISSUE TITLE
Progress output expands window horizontally

### ISSUE THREAD

**Issue by codygarver** [elementary/installer#373]
The distinst output causes the window to eventually become like 3000 chars wide. See attached screenshot.

![screenshot](https://user-images.githubusercontent.com/2166391/56564058-da9e5f00-6572-11e9-99c0-6fffe8513f60.png)

**Comment by mmstick** [comment]
You need to rebase on the current version of the installer.

**Comment by cassidyjames** [comment]
@codygarver specifically, this PR supposedly fixed it: https://github.com/pop-os/installer/pull/108

**Comment by cassidyjames** [comment]
Duplicate of #257
