### ISSUE TITLE
Super+Spacebar launches Wingpanel

### ISSUE THREAD

**Issue by codygarver** [elementary/installer#376]
I'm guessing shortcuts are coming from Gala and need to be reset to `''` while the Installer session is running?

**Comment by peteruithoven** [comment]
This was a great solution for the Greeter: https://github.com/elementary/greeter/pull/255

**Comment by cassidyjames** [comment]
@codygarver I can't reproduce this in the latest ISO

**Comment by danrabbit** [comment]
This no longer happens in the latest 6.0 daily
