### ISSUE TITLE
The installation fails with certain locales because of wrong locale code

### ISSUE THREAD

**Issue by ryonakano** [elementary/installer#379]
Originally from https://github.com/pop-os/distinst/issues/183 (which was inappropriate to file there)

**Describe the bug**
The installation successfully finishes when I choose English (en_US), but it fails when I choose other languages, at least Japanese (ja_JP) or Korean (ko_KR).

**To Reproduce**
1. Select Japanese (which is shown as "日本語") in the language list
2. Choose clean install
3. The installation begins
4. The installation fails

**Expected behavior**
The installation should finish successfully even in Japanese or Korean.

**Screenshots**
![1](https://user-images.githubusercontent.com/26003928/56810006-35380380-6870-11e9-8b84-219393aece25.png)

This is the error message which is shown when I set the language to Japanese.

![2](https://user-images.githubusercontent.com/26003928/56810008-35d09a00-6870-11e9-8c09-22579c71ec9f.png)

And this case is Korean.

**Desktop (please complete the following information):**
 - OS: elementary OS Juno (Daily 20190426) on Virtual Box 6.0.6
 - elementary Installer 1.0+r1014+pkg13\~daily\~ubuntu5.0.1
 - Distinst 0.3.2\~1555431998\~18.04~3f51803

**Additional context**
As far as seeing the log, the reason why installation fails in Japanese seems to be related to wrong locale code:

```
…
(First part omitted)

INFO: running "chroot" "/tmp/distinst.bgLvf7fm49Ya" "locale-gen" "--purge" "ja_JA.UTF-8"
WARN: /bin/bash: warning: setlocale: LC_ALL: cannot change locale (ja_JA.UTF-8)
WARN: Error: 'ja_JA.UTF-8' is not a supported language or locale
ERROR: configuring chroot error: error generating locales: command failed with exit status: exit code: 1
```

The error message says "ja_JA", which does not exist locale code (the correct locale code for Japanese is "ja_JP"). I would say some logic to set locale does not work correctly.

**Comment by ryonakano** [comment]
I think this line causes this issue:

https://github.com/elementary/installer/blob/227bb4a26db8905267cc97d3a4ad5eca46f2dcb3/src/Views/ProgressView.vala#L148

This line works fine for some languages whose language code and country code is same, e.g. Spanish (es_ES) or Dutch (de_DE). However, it does not work if the language code and country code is different, e.g. Japanese (ja_JP) or Korean (ko_KR).

**Comment by MrMarukesu** [comment]
Maybe #340 can resolve this
