### ISSUE TITLE
Smarter hostname

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#383]
Split from #377. We should grab the model number as a default hostname, i.e. `Precision-5530` or `Galago-Pro`. Ubiquity does this as a user-changable default but I think we'd be fine just doing it behind the scenes.

**Comment by btkostner** [comment]
As far as I know, there is no way to change it after install in the settings app. You can do it with terminal and it _should_ be simple, but some applications use it statically on first install or run. I personally think this should be overrideable on install.

**Comment by cassidyjames** [comment]
@btkostner considering it's not even settable in the installer now, a smarter default would still be an improvement. However, Pop!_OS and other OSes don't offer a user-settable hostname and seem to work fine; changing it via Terminal is an easy one-time change for people who would like to dive into the internals of their computer.

Something I could see being considered that we've talked about is doing a pair of model and random hash so you have unique hostnames, even for a fleet of machines of the same model. Otherwise, I don't see a strong argument for making a user decide on an implementation detail.

**Comment by cassidyjames** [comment]
Ubiquity does a couple of things:

1. Tries to get the model name from DMI, but there's a handful of special casing: https://git.launchpad.net/ubiquity/tree/ubiquity/misc.py#n618
2. If that fails, it uses `laptop-detect` and just appends `laptop` or `desktop`: https://git.launchpad.net/ubiquity/tree/ubiquity/plugins/ubi-usersetup.py#n77

I think trying DMI is worthwhile, though I'm less sure about the special casing; they obviously did it to work around weird cases but that seems annoying to maintain in the installer. I'd be more okay if it was its own library or something.

Instead of laptop-detect, `org.freedesktop.hostname1` has the `chassis` property which we could use.

**Comment by btkostner** [comment]
@cassidyjames my point is, it's easy to set in the terminal, but there is a lot of software that uses that name on first run when generating configuration. Those files are static and are not updated with a simple terminal command.

**Comment by cassidyjames** [comment]
@btkostner software like…? I've literally never come across that or had issues with changing my hostname. And regardless, that's still out of scope for this issue as there is _already_ no way to set a hostname in the installer. This doesn't change that, it just suggests making the _already hardcoded_ name a little smarter.
