### ISSUE TITLE
Respect .volumeicon

### ISSUE THREAD

**Issue by vjr** [elementary/installer#39]
Something akin to https://packaging.neon.kde.org/neon/settings.git/plain/usr/share/pixmaps/neon.png so that it shows this instead of the default linux tux icon during the install process.

edit: to clarify, i meant the icon to show the list of existing operating systems already installed.

**Comment by danrabbit** [comment]
I would think this would be an issue with neon. We should probably just respect `.VolumeIcon` and let operating systems be responsible for their own branding

**Comment by vjr** [comment]
@danrabbit I mean the icon to show during the screen which lists all existing installations. Were you talking about the scenario where pantheon-installer is used to install another distro?

**Comment by danrabbit** [comment]
Nope, we're talking about the same case. There should be a file called `.VolumeIcon` on the root of that partition to supply branding.

I think it's not a reasonable scope that we provide branded icons for every possible operating system.

**Comment by vjr** [comment]
Oh I see, is there some sort of spec for VolumeIcon? I just placed the PNG file there as `.VolumeIcon` and it doesn't show in the installer - but yeah - I know this is an early experimental stage. :-)

**Comment by danrabbit** [comment]
Changed title to reflect :)

**Comment by vjr** [comment]
Filed this ticket for KDE Neon https://bugs.kde.org/show_bug.cgi?id=381893 and will submit a PR for the installer here shortly :-)

**Comment by vjr** [comment]
The PR is merged but I have a pending question about whether it's enough to just look for `.VolumeIcon.png` or should I also be looking for `.VolumeIcon` for which, if so, I can submit another PR.

**Comment by codygarver** [comment]
The original issue here is fixed. If it turns out there's a reason to support more filesnames then a new issued should be opened.
