### ISSUE TITLE
How to install without any bootloader

### ISSUE THREAD

**Issue by MayusYT** [elementary/installer#390]
Hi, 
I currently want to install Pop!_OS (which apparently uses this installer) on an SSD that already has the Clover bootloader with a Grub EFI file on it. I already got ubuntu to boot with that setup.

Because I heard that this installer automatically installs `systemd-boot`, I'm kinda worried that this will overwrite my current bootloader setup. When I select my current bootloader partition (with clover/grub on it), it says that it's too small. Is there a way to let the installer completely ignore the bootloader?

Thanks in advance!

**Comment by mmstick** [comment]
The Pop!_OS installer is practically a completely different code base at this point, so there's little relation to the elementary repo of the installer. You'd want to post this issue in `pop-os/installer`.

However, the nature of EFI is that bootloaders do not conflict with or modify each other. They can coexist simultaneously on the same EFI partition, or may even be spread across multiple EFI partitions on multiple drives. So there's no need to install Pop!_OS without a bootloader.
