### ISSUE TITLE
[Feature] Support OpenBSD-based Distros

### ISSUE THREAD

**Issue by jkhgvfgvsth** [elementary/installer#392]
**Functionality**: Support OpenBSD based OSes

___________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/76651860-feature-support-openbsd-based-distros)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=76651860)](https://www.bountysource.com/issues/76651860-feature-support-openbsd-based-distros)

**Comment by cassidyjames** [comment]
This would need to be filed against the installer backend, [distinst](https://github.com/pop-os/distinst).
