### ISSUE TITLE
HiDPI not detected

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#394]
Not sure what compositor we're running during this session, but it doesn't seem like HiDPI is being detected

**Comment by cassidyjames** [comment]
@danrabbit if I recall correctly from Pop!_OS, this was due to the installer launching too quickly before GSD was fully initialized or something… I believe they just did a dumb timeout to wait, but did we also have this issue in Greeter?

**Comment by danrabbit** [comment]
In the greeter we listen to the scale factor just to maximize the window, but one thing to check is if GSD is running in the session
