### ISSUE TITLE
Check mark in "Advanced" isn't always clearly visible

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#395]
It's a green check and sometimes it gets put on a green bar. We should probably use the color icon here to ensure contrast

**Comment by cassidyjames** [comment]
@danrabbit I think my design was to use a monochrome icon… let me see if I can find that or the CSS snippet…

**Comment by cassidyjames** [comment]
Ah it was just something like this:

https://github.com/pop-os/installer/blob/f912be945f55bab1276873b6c770241356e9b5a9/data/application.css#L36-L39
