### ISSUE TITLE
Wireless connection data is not retained after rebooting from installer session

### ISSUE THREAD

**Issue by ryonakano** [elementary/installer#401]
The new Installer does not retain the wireless connection data (SSID and password) after rebooting from installer session to user session, while the current installer (Ubiquity) does this.

**Comment by cassidyjames** [comment]
The intent is that we don't even connect to a network or anything with the new installer; how are you connecting?

**Comment by ryonakano** [comment]
Although I've never tested to run installation without connecting to Internet, I tried if this issue fixed in the latest Beta2 iso but it still occurs for me.

**Comment by ryonakano** [comment]
Closing since the new Installer don't require internet connection
