### ISSUE TITLE
No HiDPI detection in installer session 

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#414]
In the latest 6.0 daily the installer session is LoDPI

**Comment by cassidyjames** [comment]
This probably means: 

1. GSD isn't running,
2. The right GSD plugin isn't loaded, or
3. The installer is starting before GSD

I think 3 is what was happening in Pop!_OS and is why they patched in a timeout to delay launching the installer (which seems like a bad hack to me).

**Comment by danrabbit** [comment]
It sounds like HiDPI detection moved into Mutter, so this may actually be an issue with the greeter compositor
