### ISSUE TITLE
Fails to build on Launchpad

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#423]
```
In file included from src/25a6634@@io.elementary.installer@exe/Widgets/LayoutWidget.c:24:
/usr/include/libgnomekbd/gkbd-keyboard-drawing.h:25:10: fatal error: X11/extensions/XKBgeom.h: No such file or directory
   25 | #include <X11/extensions/XKBgeom.h>
```

https://launchpadlibrarian.net/467044895/buildlog_ubuntu-focal-amd64.io.elementary.installer_1.0+r1108+pkg19~daily~ubuntu6.0.1_BUILDING.txt.gz

**Comment by davidmhewitt** [comment]
That file is supposed to be in `libx11-dev` and on my installed focal system that points at ubuntu mirrors on the internet, I have version `1.6.9-2` installed and it includes that header file.

Looking at the launchpad log, version `1.6.8-1` was installed from `http://ftpmaster.internal/ubuntu`. I would guess that version of the package is broken somehow and the internal launchpad repos haven't been synced yet.

**Comment by davidmhewitt** [comment]
Latest rebuild has resolved this issue.
