### ISSUE TITLE
Distinst pointer in FFI is null

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#430]
Alright drives show and HiDPI works

now I get:
libdistinst: pointer in FFI is null
And then
partitioning error: vgchange failed with status: 5 (Input/Output error (os error 5))

Tried again and got:

Error: configuring chroot error: error installing packages: command failed with exit status: exit code: 100

**Comment by meisenzahl** [comment]
@danrabbit is this still an issue?

**Comment by davidmhewitt** [comment]
I'm going to close this as I've been doing a lot of work and experimenting with the installer recently and it's not something I've seen/heard. We can always re-open if it re-occurs.
