### ISSUE TITLE
Some translation bugs into french

### ISSUE THREAD

**Issue by roxfr** [elementary/installer#431]
Hi,
Here are some translation bugs (see images below).
Regards,
roxfr

1)
<a href="https://zupimages.net/viewer.php?id=20/15/g2o0.png"><img src="https://zupimages.net/up/20/15/g2o0.png" alt="" /></a>

2)
<a href="https://zupimages.net/viewer.php?id=20/15/0db5.png"><img src="https://zupimages.net/up/20/15/0db5.png" alt="" /></a>

Infos : 
<a href="https://zupimages.net/viewer.php?id=20/15/erc7.png"><img src="https://zupimages.net/up/20/15/erc7.png" alt="" /></a>

**Comment by ryonakano** [comment]
The current installer (called "Ubiquity") is not developed by elementary and its translation is managed at [Launchpad](https://translations.launchpad.net/ubuntu/+source/ubiquity). Closing as "Out of Scope"

**Comment by roxfr** [comment]
Ok i created a bug report in launchpad

https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1872170

**Comment by ryonakano** [comment]
Actually they're already translated: https://translations.launchpad.net/ubuntu/focal/+source/ubiquity/+pots/ubiquity-debconf/fr/+translate?batch=10&show=all&search=skip

It should be shown as translated in the next release of Ubiquity.

**Comment by roxfr** [comment]
Ok thank you :-)
