### ISSUE TITLE
System doesn't reboot after installation is finished

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/installer#435]
Everytime I install EOS and the installation is finished. When I click on "restart system" or whatever it is called, the normal black screen shows up with " remove media and reboot", I would remove the USB stick and hit enter, but nothing happens. It just hangs there forever until I force shut the computer down. I have tried ctrl+alt+F3/F4, but that takes me to another black screen with only a blinking cursor. Is there something else I'd need to do beside removing the USB stick to reboot my system or is this is a bug? Not sure to be honest, but this happens literally everytime I install EOS. Thought I'd bring this to your attention.
Thank you.

**Comment by cassidyjames** [comment]
This repository is for the new (unreleased) installer, which I _believe_ should resolve that issue as it just automatically reboots.

**Comment by KarkanAlzwayed** [comment]
> This repository is for the new (unreleased) installer, which I _believe_ should resolve that issue as it just automatically reboots.

There was no option in settings/about/report a problem for the installer. I came to EOS github and found the installer and still only options I found were Juno and the unreleased one. I opened a "new issue" and happened to be on the unreleased. Anyway, are you saying that EOS 6.0 is going to have a new installer that fixes this issue? 
Thanks.

**Comment by cassidyjames** [comment]
Yes, 6.0 will have the new installer and won't reboot in the same way as 5.x.
