### ISSUE TITLE
6.0 Installer Fails When LVM Devices Are Present/Mounted

### ISSUE THREAD

**Issue by Schykle** [elementary/installer#438]
6.0 installer from multiple daily images. NOT filed against the existing installer.

**Describe the bug**
Using the "Clean Install" option fails if LVM volumes are present on the disk, in this case, LVM volumes that were created with the same option prior, but installing over fails.

**To Reproduce**
1. Install normally (Clean Install) or with existing LVM volumes
2. Reinstall via the same means (Clean Install)
3. Partitioning fails

**Expected behavior**
LVM volumes on the disk being installed to should be disabled/removed prior to attempting partitioning.

**Additional context**
It might be worth noting that I was able to work around this by manually controlling the LVM volumes the installer had created in a previous install by running `sudo vgchange -an data && sudo lvremove data`, and then proceeding through the installer. Wiped/clean disks or disks with no LVM enablement don't exhibit this behaviour on my machines.

**Comment by meisenzahl** [comment]
I am not able to reproduce this issue with `elementaryos-6.0-daily.20201207`. I installed it twice with clean install and encryption. Worked flawlessly.

@Schykle can you confirm this?

**Comment by oVerde** [comment]
@meisenzahl I went and downloaded the said version to try too, and didn't work

**Comment by c0ppo** [comment]
I own new Dell XPS 15 9500. Even after removing LVM disks, I simply can't get EOS 6.0 to install. No matter what I do. I've tried every possible scenario, but nothing worked.

**Comment by disaster123** [comment]
Same issue here. To solve it I went to advanced unmounted and removed all partitions and went back to clean install

**Comment by alx242** [comment]
I have tried multiple (5-6) versions and can't install eOS6 with full disk encryption. I do this on a separate partition from my ordinary eOS5 installation. Every time I end up in a state where grub can't find the kernel and launch the OS. If I do this without full disk encryption everything is fine.

This has to be the prioritized issue since it constantly creates a broken system.

**Comment by pongloongyeat** [comment]
> I have tried multiple (5-6) versions and can't install eOS6 with full disk encryption.

This is a known issue #457

**Comment by danrabbit** [comment]
@Schykle can you check this with the latest daily? It sounds like @cassidyjames tested this today and couldn't reproduce.

Though, #457 seems to still be valid

**Comment by Schykle** [comment]
Sorry for the delayed response, wanted to test on multiple machines just to be sure. It appears I cannot reproduce the issue anymore myself either.
