### ISSUE TITLE
Selecting disk encryption prevents installation to finish. (elementaryos-6.0-daily.20201107)

### ISSUE THREAD

**Issue by brodock** [elementary/installer#459]
**Describe the bug**
Selecting disk encryption prevents installation to finish. (elementaryos-6.0-daily.20201107)

**To Reproduce**
1. Creates a new VM in Virtualbox with EFI enabled
2. Uses elementaryos-6.0-daily.20201107 build
3. Perform a clean installation
4. Select an encryption password

**Expected behavior**
Installation should finish with success

**Screenshots**
![image](https://user-images.githubusercontent.com/20575/98455346-87e5c180-216f-11eb-8f38-9bf03cbbdac4.png)

**Additional context**
Without enabling encryption it finishes installation, but then image tries to mount the encrypted volume which doesnt exist, so its impossible to run ElementaryOS 6

**Comment by cassidyjames** [comment]
Ah this is a duplicate of #457
