### ISSUE TITLE
Installation window not horizontally aligned

### ISSUE THREAD

**Issue by florisvlasveld** [elementary/installer#463]
When installing Elementary OS 6.0 build 20201205 on a 13'' Dell XPS 9300, the installation window is not horizontally aligned. Instead, the window is positioned slightly too much to the right side of the screen.

![96A5756D-6D0F-45C4-9BB1-8DDC40D358F0](https://user-images.githubusercontent.com/1478713/101244463-000bbc80-3707-11eb-8627-11c631ed6d14.jpeg)

**Comment by hanaral** [comment]
I think that this sort of thing leaves an impression on new users, just like the unmovable perfectly centred installer macOS has.

**Comment by cassidyjames** [comment]
Can we set the window to "always centered", and does the window manager here respect that? I think the issue is that the window grew horizontally after it was originally drawn.

**Comment by danrabbit** [comment]
I'm not sure there's a way to make the window resize from the center

**Comment by hanaral** [comment]
> Can we set the window to "always centered", and does the window manager here respect that? I think the issue is that the window grew horizontally after it was originally drawn.

Is there actually no way to set a tested largest possible size, or to artifically constrain the window's maximum size? I'd find it hard to believe there isn't a solution for this

**Comment by danrabbit** [comment]
It depends on what is stretching the window. A big problem is that much of the app can't be constructed until after a language is chosen and so text wrapping may occur at different widths here. So finding the reason the window is being stretched is probably the hardest part

**Comment by hanaral** [comment]
>It depends on what is stretching the window. A big problem is that much of the app can't be constructed until after a language is chosen and so text wrapping may occur at different widths here. So finding the reason the window is being stretched is probably the hardest part

@danrabbit I just tested the installer.
The window size changes when the “Try or Install” is shown (at least when set to English), before that it’s perfectly centred as far as I can tell.
I presume that what’s causing it is either the installation buttons or the “Try or Install” text.

**Comment by danrabbit** [comment]
We've gone through and I believe have now found all views that were forcing the window to resize. This should theoretically now be fixed
