### ISSUE TITLE
Automatically prompt for screen reader after a timeout

### ISSUE THREAD

**Issue by danirabbit** [elementary/installer#471]
A person with low vision pointed out that a feature they heavily appreciate in macOS is that the screen reader is automatically enabled after a certain amount of inactivity at the installer. Turning on the screen reader is the absolute most important first step for them to be able to interact with the computer. Without it, they pointed out that they would have to rely on a sighted person to set up their computer for them, which is a huge hindrance for them.

**Comment by danrabbit** [comment]
After watching a video about how this works in macOS, it looks like what they do is first wait about 10 seconds and then it will play an audio instruction to enable the screen reader using a keyboard shortcut. This way we're able to get explicit confirmation from the user that they want to enable the screen reader and haven't just stepped away and become confused about why everything is being read aloud

**Comment by danrabbit** [comment]
Blocked by https://github.com/elementary/greeter/issues/610

**Comment by danirabbit** [comment]
I can confirm that the screen reader shortcut works in the Installer now, so we just need to play the instruction after a timeout
