### ISSUE TITLE
Installed system is not signed for secure boot

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/installer#473]
It seems that the .iso image is secure boot capable as it will boot fine with secure boot enabled. 

But after installation, trying to reboot into the installed system results in a secure boot failure. This is probably something to do with the way distinst is setting up the bootloader, as I can "fix" it by doing the following:

- Disable secure boot
- Boot into installed system
- Run `sudo grub-install`
- Reboot
- Enable secure boot
- Profit

**Comment by davidmhewitt** [comment]
Found the issue, PR created upstream:
https://github.com/pop-os/distinst/pull/244

**Comment by davidmhewitt** [comment]
Upstream PR merged. 

@danrabbit When you get chance, can you copy in the latest snapshot of distinst? Then we should be able to close this.

**Comment by danrabbit** [comment]
Copy has been requested!

**Comment by danrabbit** [comment]
Done :)
