### ISSUE TITLE
Icons/Images not shown in Installer

### ISSUE THREAD

**Issue by marbetschar** [elementary/installer#477]
**Describe the bug**

There are several Icons/Pictures missing/not displayed and the Installer shows a Debian logo during OS installation. Did not found an existing issue for this, therefore logging here so we can keep track.

**Comment by davidmhewitt** [comment]
This is essentially https://github.com/elementary/default-settings/issues/214

However, it's fine to track it here too as it'll probably need work in both places to fix. It's something I'm looking at this weekend.
