### ISSUE TITLE
Installer doesn't understand LVM, and doesn't detect existing volumes/filesystems.

### ISSUE THREAD

**Issue by Bananaman** [elementary/installer#492]
**Describe the bug**
The installer doesn't understand LVM partitions, treating them as "filesystem: none", and overwriting their existing contents. This held true regardless of whether the hierarchy was `SSD -> LVM -> ext4` or `SSD -> LUKS -> LVM -> ext4`. It's obviously a huge drawback if the user wants to preserve their existing filesystem and LVM hierarchy to avoid data loss when installing the operating system.

**Expected behavior**
Installer should detect the LVM volume group and mount the whole hierarchy and detect all of the LVM logical volumes and their filesystems.

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Version 20.10
 
 **Longer explanation which contains a list of things I've tried:**
I've found a big flaw in the installer's detection of existing filesystems on top of LUKS+LVM. I made a custom SSD -> LUKS with 4096 byte sectors, to match the underlying SSD's physical sector size. -> LVM volume -> mkfs.ext4 with 4096 byte block size.

But the installer only sees the LUKS, unlocks it, sees the LVM volume, but doesn't see the existing ext4 filesystem. Instead it forcibly reformats the "blank" (in its opinion) LVM volume as ext4.

I am just lucky that ext4 defaults to 4096 byte blocks on 64-bit machines, which is the block size I need, but this lack of manual reformatting control isn't ideal. Because it's a **very bad** thing if a person wants to reinstall the OS without reformatting the filesystem (such as if they've kept a copy of their user data on the disk and just erased the system folders manually, and then want to reinstall on top of that without reformatting, to keep all data). The current flawed installer forcibly reformats the entire filesystem and loses all data.

Any ideas / fixes for this installer issue? If it could just recognize that there's already an ext4 filesystem on the LUKS->LVM device it mounted, it'd all be good.

Attempted workarounds and tests:

- I tried going to the "custom install partitions" step of the installer, alt-tabbed, opened terminal, ran `mkdir /mnt/r && mount -t auto -v /dev/mapper/data-root /mnt/r` to see if forcibly mounting the filesystem makes the installer understand that it already has ext4. But it didn't refresh the installer window. So I clicked on "manage partitions" in the installer and then closed GParted immediately to force a GUI partition refresh, but that just caused the LUKS/LVM to be auto-unmounted by the installer.
- As a test, I made a LUKS volume *without LVM on top of it*, and wrote an ext4 filesystem directly to the LUKS volume. The installer properly detected that one as ext4 as soon as it mounted the LUKS partition in the custom installation GUI, and properly offered me to keep the existing data (not formatting the ext4 again). (Just as an extra test, I tried installating this way directly on LUKS, and it wasn't bootable).
- As another test I tried LUKS -> LVM -> partition table (gpt) -> Ext4, hoping that having a partition table on the LVM volume would make the installer understand that an ext4 partition exists... but this test got stuck in a dead end because it was impossible to deactivate the LVM volumes to let the installer take over. Nothing was mounted but the kernel just refused to let go of the LVM, most likely due to the kernel actively using/reading the partition table, so not even the installer could access it when I did this test... I gave up on that thought.
- As a final test, I skipped encryption and just did SSD partition table -> LVM -> ext4. This failed in the exact same SPECTACULAR way: The installer showed the entire partition that LVM sits on, showing it as "filesystem: none" (in the installer GUI's own words), and only offered one choice: Reformat that partition. I tried this (thank God for VMs), and it failed spectacularly, crashing the installation process with an error from mkfs.ext4 saying "Operation not permitted" since it detected the attempt to overwrite the whole LVM container hierarchy with a basic ext4 partition instead.

Normal, unencrypted disks with direct ext4 filesystems that are marked in the partition table, work properly in the installer. It offers those as an installation target without forcibly reformatting them. Only filesystems on top of LVM suffers from this issue.

**So the core issue that I've now narrowed down here is that when the installer encounters LVM (regardless of whether it's directly on the disk, or on top of LUKS), it DOESN'T analyze the existing filesystems on the LVM logical volumes whatsoever. It just treats LVM data structures as blank, unformatted space without any filesystems. On the other hand, the installer properly detects filesystems that are directly on top of LUKS (no LVM), or are marked directly in a drive's partition table (ie an unencrypted disk), and will then understand that filesystems already exist on a given block device. It seems like the necessary solution will be to make the installer capable of detecting lvm in a partition table partition/on LUKS, and probing it to detect all logical volumes and their filesystems and offering *those* as targets.**

The main drawbacks of the installer's current inability to understand LVM are:

- Inability to pre-format your filesystem with desired filesystem creation flags. Because it'll always be forcibly reformatted using default installer settings instead.
- Data loss if you re-/install an OS onto the LVM container. Because the existing filesystem will always be forcibly reformatted.
- Inability to do a "refresh/fix installation" via the rescue partition / live CD to fix the operating system. Because the installer doesn't understand that you have an existing filesystem on top of LVM and therefore it doesn't see your existing Linux installation.

This bug may also require fixes in https://github.com/pop-os/distinst, so I'll be reporting it there too and cross-linking now.

**Comment by Bananaman** [comment]
News update: @mmstick has discovered and fixed the issues in the `distinst` project.

It seems like the Elementary Installer GUI itself doesn't need any patches. But I can't say that for sure (since `Pop!_OS` uses a fork of the GUI), so after you've reviewed this issue and checked his patches, feel free to close this ticket if everything is okay in Elementary Installer.

Take care! :-)

**Comment by danrabbit** [comment]
Looks like the version of distinst that we have imported was built in June, so that should contain the fix. Thanks for following up on this issue upstream!

Closing as fixed
