### ISSUE TITLE
Make a more obvious notificiation when Wireless connection was successful

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/installer#505]
When I enter my Wireless password during the installation correctly, it silently accepts it and I'm not sure whether connection was successful.

When the elementary package servers can be accessed successfully, the connection dialog should show a green "OK" sign or something similar

**Comment by cassidyjames** [comment]
@CodingSpiderFox I presume this is for elementary OS 5? In the future please use the issue templates; elementary OS 6 uses an entirely new installer that does not require any Internet connection.
