### ISSUE TITLE
Confusing headers in the UI

### ISSUE THREAD

**Issue by Loreno10** [elementary/installer#515]
**Describe the bug**
I think that the new UI is a bit confusing. The description below refers to a screenshot that I posted in the _Screenshots_ section.

I was sure that the "Try or Install" header on the left is actually a button, and that there are in total 4 options to choose from:
 - the "Try or Install" header
 - the 3 other buttons on the left

I think that the header lacks some "contrast" to distinguish it from the actual content that the user is supposed to interact with.

Another issue that can be seen in the screenshot are the horizontal margins - they're way too small.

**To Reproduce**
Ru the installer for eOS6

**Expected behavior**
The UI should make it clear what is the header, and what are the buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/10273406/116808464-32480b80-ab39-11eb-9c64-ccfe7fd726af.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Loreno10** [comment]
@cassidyjames Don't you think the margin in the installer window is too tiny? Is it a known issue or should I open a new one for it?

**Comment by cassidyjames** [comment]
@Loreno10 it matches the dialog styling throughout the OS.
