### ISSUE TITLE
Language View: Geolocate for language selection

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#52]
We should try and use GeoClue to bubble the relevant languages to the top; we don't need an Internet connection if GeoClue can use other signals to determine a "precise enough" location. And we can't connect to the Internet first anyway since language selection must be first.

**Comment by davidmhewitt** [comment]
The only way GeoClue will be able to get a location at all without a working internet connection is if the device has a GPS receiver that it supports.

Looking at the nearby 3g towers/WiFi hotspots to determine location still requires an internet connection as it has to look up the MAC addresses etc.. in the online Mozilla DB. There is no offline data it can use to triangulate hotspots/towers.

This would work with wired devices that automatically set up the net connection, GeoClue would be able to use the public internet IP to hopefully get a semi-accurate location to the country level. I don't think this would work at all for laptops with only a WiFi adapter. Maybe needs some more design as to what happens in the various cases?

**Comment by danrabbit** [comment]
Closing since we're starting to get to the point where it's unclear who this feature would actually benefit. We're already sorting the most commonly spoken languages to the top of the list
