### ISSUE TITLE
Second step of VariantWidget not focused

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#539]
I believe we used to have the second step of the variant widgets (used on the Language and Keyboard views) focused so you could easily use the keyboard to either arrow down to another option or press Enter to activate the pre-selected option. 

But now that second step list does not have focus, requiring a click or a few presses of the Tab key.

**To Reproduce**

1. Run the installer
2. Select a language with variants (e.g. English)
3. Look at the variant list to see it's not focused

**Expected behavior**

The second step of VariantWidgets should be focused when switching to them

**Comment by danirabbit** [comment]
Fixed in #791
