### ISSUE TITLE
Custom Install -> Back -> Try Elementary OS Button Broken

### ISSUE THREAD

**Issue by Denbox** [elementary/installer#545]
**Describe the bug**
Selecting custom install option, going back, then clicking the Try Elementary OS button returns to the custom install screen.

**To Reproduce**
1. Boot Elementary OS Install Media
2. Click through Language Prompts
3. Click custom install
4. Click Back
5. Click Try Elementary OS

**Expected behavior**
Clicking Try Elementary OS launches OS, doesn't go to custom install

**Desktop (please complete the following information):**
 - OS: Elementary OS 6 (5/9/21)

**Comment by danrabbit** [comment]
Fixed in #554
