### ISSUE TITLE
Keyboard Layout selection

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#59]
We need to be able to choose a keyboard layout for the live session and to set the default for the installed system. This should come right after the language screen.

**Comment by cassidyjames** [comment]
![img_20170828_132930](https://user-images.githubusercontent.com/611168/29790124-da1269c6-8bf5-11e7-84cb-f3a41c751e7b.jpg)

**Comment by cassidyjames** [comment]
If we want to preview the keyboard layout, we can use GkbdKeyboardDrawing (like the layout switcher indicator) in an inline toolbar at the bottom (outside the stack).

**Comment by danrabbit** [comment]
Fixed in #60
