### ISSUE TITLE
Laptop goes to standby during installation process

### ISSUE THREAD

**Issue by pferrucci** [elementary/installer#590]
## What Happened
In the installation process, I needed to change my partition using Gparted. The partition move process lasted for 5 hours.
After a while my laptop would go to standby, freezing the gparted move process. So I have to continuously move my mouse to avoid that.

## Expected Behavior
As the installation may last for many hours, standby should be disabled.

## Steps to Reproduce
1. On a laptop, on the partition selection window, select the "change partitions" button
2. select some very long action (I was using a mecanical HD)
3. leave the laptop alone. It will go to sleep at some point

## Platform Information
eOS Odin
A Dell Laptop.

**Comment by eppixx** [comment]
The issue mentions a laptop, but it also happened on my desktop pc

**Comment by danirabbit** [comment]
Just noting here that the Installer side is theoretically fixed, but we need https://github.com/elementary/greeter/issues/560 to be solved for it to fully fixed
