### ISSUE TITLE
Elementary OS 6 fails to install on computers that only have legacy BIOS mode.

### ISSUE THREAD

**Issue by LuisMi1245** [elementary/installer#599]
## What Happened
On my computer that only has Legacy BIOS mode, when I try to install Elementary OS 6, right after pressing the install system button, the installer immediately throws an error as shown in the attached image: 

![20210813_192553](https://user-images.githubusercontent.com/35621197/129429681-c7fcd892-9b20-4cbe-bf20-b256396ae824.jpg)

I have tried to install EOS6 with two hard disks, one internal and one external via usb. For both disks the installation gives me the same error; I have fully formatted both disks using MBR partition tables on the first try, and then GPT (creating a fat32 partition, flag: bios_grub to solve the GPT compatibility problem).
I have used the "Erase entire disk and install" mode to get Elementary to do the proper configuration, but it also fails. I have used the manual partitioning mode, but it also fails. It only boots in demo mode.

## Expected Behavior
The installation of Elementary Os Hera does work perfectly on this same hardware, however I preferred to use Ubuntu 21.04 until the problem is solved or I buy a new PC. 

## Steps to Reproduce

1. Create the bootable USB using the official elementary.io guide (using Balena Etcher of course).
2. Restart the computer and press F9 to select the drive you want to boot, and select the USB with elementary os 6.
3. Set the language (in Spanish) and Latin American keyboard. 
4. Use the installation mode: "Erase all the disk and install". I select the hard disk of my computer.
5. I select not to encrypt the disk.
6. I press the install button.
7. A second later, the error shown in the image appears.  

### Logs

![20210813_192648](https://user-images.githubusercontent.com/35621197/129430162-6aa0e968-3018-4b7a-86fe-d1d7dd09ce0c.jpg)
![20210813_192744](https://user-images.githubusercontent.com/35621197/129430165-1c9f6335-9b15-49f3-a229-f3e9802c68c4.jpg)
![20210813_192834](https://user-images.githubusercontent.com/35621197/129430168-36e86bf0-b4be-4ee4-bb3a-0242e955d244.jpg)

## Platform Information

My Laptop is the: HP-1000 (Only supports Legacy BIOS mode and works with Elementary OS Hera), 64 bits. 
Hardware:
Intel Core I5 - Sandy Bridge (2450M)
8GB RAM,
512GB HDD.

**Comment by cassidyjames** [comment]
@LuisMi1245 it looks like this is actually an issue with the generated hostname for your machine, hence that last line of the error. @davidmhewitt has reported a specific fix in #600.

**Comment by davidmhewitt** [comment]
I believe this should be fixed with the latest iso released a few days ago. If you download and re-test it and the issue still persists, please let us know and we'll re-open the issue and investigate more.
