### ISSUE TITLE
Use Distinst.validate_hostname to check generated hostname

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/installer#600]
## Problem
Issues like #599 look like we're managing to generate an invalid hostname on certain hardware. 

## Proposal
Distinst has a built in method to check a hostname is valid, so we should use that and fall back to just `elementary-os` or something if it's not valid.

**Comment by meisenzahl** [comment]
I think that we should also use this in https://github.com/elementary/initial-setup/pull/113

**Comment by davidmhewitt** [comment]
I don't think initial-setup should depend on distinst. It would be pretty simple to re-implement the specification for hostname checking. It's essentially:

- Can only contain alphanumeric characters, periods (.) and hyphens (-)
- Must not start or end with a period or hyphen
