### ISSUE TITLE
Preload apps with OEM install. Like what was possible with ubiquity.

### ISSUE THREAD

**Issue by reesericci** [elementary/installer#606]
## Problem

I would like to be able to preload apps onto the device which will show up once the user sets up their account.

## Proposal

Do it in a similar way that ubiquity did it. I could log in to a temporary user account and install all the apps and then log out and have an initial setup.

## Prior Art

Ubiquity

**Comment by cassidyjames** [comment]
This is answered here: https://github.com/elementary/os/wiki/Creating-a-Custom-Image

**Comment by reesericci** [comment]
coolio
