### ISSUE TITLE
7.0 - Loop when attempting to install with encryption

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/installer#623]
### What Happened?

When attempting to use full-disk encryption the install reaches `executing cryptsetup` and then seems to crash and restart the demo iso.
Here's a video of this happening: https://youtu.be/Ix6rMbSYBiQ

I'm aware this could be a VM only issue but I have no spare drives to use to find out.

### Steps to Reproduce

1. Load up elementaryos-7.0-daily.20211105.iso in a virtual machine
2. Attempt to install with encryption

### Expected Behavior

Install without issues :woman_shrugging: 

### OS Version

Other Linux

### Software Version

Compiled from git

### Hardware Info

Gnome boxes, 2GB, QEMU

**Comment by davidmhewitt** [comment]
Interestingly, I can't reproduce this.

I'm using the same iso file, GNOME Boxes, VM with 2GB of RAM and I've just successfully installed with encryption.

Is there anything else I might be able to try to reproduce this? What OS did you choose when you created the Boxes VM? Did you use any special characters in your encryption password?

**Comment by davidmhewitt** [comment]
Well, I say I've successfully installed...

I haven't, it seems to have hung much later in the process :sweat_smile: 

But it's definitely got past the stage of partitioning and setting up the encryption without hard resetting the VM.

**Comment by ChildishGiant** [comment]
> What OS did you choose when you created the Boxes VM? Did you use any special characters in your encryption password?

I used Juno, maybe there's the issue. The password was just alphanumeric

**Comment by davidmhewitt** [comment]
My issue with installing turned out to be RAM related, I think. I got past the hang I was experiencing with 4GB of RAM.

I used whatever the latest Ubuntu was as the OS selection when I installed. I'd be interested to hear if you doing the same resolves the issue for you.

**Comment by ChildishGiant** [comment]
Can confirm this was an issue caused by using the Juno base in boxes. Using the ubuntu 21.04 base solved it and I didn't run into the ram issue you mention
