### ISSUE TITLE
Boot partition too small (or too many kernel versions installed)

### ISSUE THREAD

**Issue by Letterus** [elementary/installer#627]
### What Happened?

I installed elementary OS 6 using the standard partition layout. I updated and installed newer versions of the kernel. It seems older versions are not deleted early enough… boot partition runs full every few updates. I receive a warning (which is nice!), but I need to manually remove old kernel versions.

### Steps to Reproduce

s. above.

### Expected Behavior

Either provide a boot partition big enough to hold the number of kernels Ubuntu provides or limit the number of kernel versions/automatically remove older ones.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by 4jNsY6fCVqZv** [comment]
Could you imagine closing your issue as a duplicate in favor of https://github.com/elementary/triage/issues/91 and https://github.com/elementary/installer/issues/506?

**Comment by Letterus** [comment]
Apparently this is a duplicate of elementary/triage#91 and #506. Closing this issue. Am just wondering those are not fixed yet, because these issues definitely break updates quite soon after first install.
