### ISSUE TITLE
No option to specify drive where bootloader is installed

### ISSUE THREAD

**Issue by drws** [elementary/installer#645]
### What Happened?

I'm trying to install Elementary OS to a bit unusual drive/partition layout and I need to be able to select the device to which the bootloader is installed. This is a standard feature in other installers.

### Steps to Reproduce

1. Boot Elementary OS ISO and start installing 
2. When partition layout is configured (last step), try to convince the installer to install the bootleoader somewhere else other than the drive where the root partition is.

### Expected Behavior

One should be able to select the device to which the bootloader is installed.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

I have two drives: `/dev/sda` and `/dev/sdb`. I would like to install Elementary OS's root to `/dev/sda` while I would like to install its bootloader to `/dev/sdb`. This is possible in other distros' GUI installers.

**Comment by danirabbit** [comment]
Maybe a dupicate of #597 ?

**Comment by drws** [comment]
Thanks for catching it!
