### ISSUE TITLE
Computer suspends during installation

### ISSUE THREAD

**Issue by drws** [elementary/installer#646]
### What Happened?

I was installing Elementary OS to a bit slower machine, so it took a bit of time. During `squashfs` extraction the computer went to sleep because installer does not prevent that.

### Steps to Reproduce

1. Start Elementary OS installation on a slower machine
2. If the installation takes enough time, computer will suspend

### Expected Behavior

I would expect the installer to prevent sleeping at least during the installation process if not the whole time the installer is running.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
This is a duplicate of #590
