### ISSUE TITLE
Keyboard View: Keyboard layout preview is blank

### ISSUE THREAD

**Issue by danrabbit** [elementary/installer#65]
It should show the keyboard map for the selected layout

**Comment by danrabbit** [comment]
Looks like the indicator is launching `gkbd-keyboard-display` https://github.com/elementary/wingpanel-indicator-keyboard/blob/master/src/Indicator.vala#L93

**Comment by davidmhewitt** [comment]
Beware of this issue however:
https://github.com/elementary/wingpanel-indicator-keyboard/issues/22

**Comment by danrabbit** [comment]
Yeah I'm sure there's probably a way to access this via library which is much more sane

**Comment by davidmhewitt** [comment]
Looks like there is, might need to write a little vapi.

I'll have a look at doing that now for the branch in the switchboard keyboard plug and let you know how I get on.
