### ISSUE TITLE
Support installer partition styling

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#698]
I _think_ this was supported by the old stylesheet. We should make sure it works in the new one, or ship the styles in the installer itself.

![Photo of unstyled partitions in Installer](https://user-images.githubusercontent.com/611168/97752828-66733e80-1aba-11eb-990d-4933eb4bfd48.jpg)

**Comment by danirabbit** [comment]
Not sure when this was fixed, but it was fixed
