### ISSUE TITLE
Double clicking the language in first step leads to empty select list in next step

### ISSUE THREAD

**Issue by spotlesscoder** [elementary/installer#745]
### What Happened?

No selection options available in second step of installer
![image](https://github.com/elementary/installer/assets/25173078/e3f3dd28-c9a7-4a7d-a90e-16c8b8309183)

### Steps to Reproduce

Download elementaryOS 7.1 official ISO
Start install in virtualbox 7.0.12
Double click the first entry "English..." in first step
![image](https://github.com/elementary/installer/assets/25173078/d93fbb21-3196-4a60-a54d-0f4da52cff5e)

### Expected Behavior

The usual selection steps that are correctly appearing on single click are also appearing on double click
![image](https://github.com/elementary/installer/assets/25173078/b53677cd-6d2e-4127-81d1-be60243bf8a8)

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by alopix** [comment]
Had the same experience just now trying to install.

**Comment by ryonakano** [comment]
I was able to reproduce this with the OS 8 Early Access:

![image](https://github.com/user-attachments/assets/afa3aa37-5c98-4473-aa7b-2c05eda61842)

BTW this issue is really hard to reproduce because double-click sometimes looks like recognized as a single-click and languages are correctly listed.

**Comment by spotlesscoder** [comment]
Occurred again in elementaryOS 8 installed
