### ISSUE TITLE
Ubuntu Logo on in-progress view 

### ISSUE THREAD

**Issue by danirabbit** [elementary/installer#747]
### What Happened?

There’s an Ubuntu logo in the in-progress view of the installer instead of the elementary logo

### Steps to Reproduce

![Screenshot from 2024-01-09 10 19 42](https://github.com/elementary/installer/assets/7277719/cbbaa7ce-7854-4fe2-a28b-4f46cac57636)

### Expected Behavior

Should be the elementary logo. Need to find out which package is adding this Ubuntu logo and patch/remove/something 

### OS Version

Early Access

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
Not sure if its related but System Settings show  this:
![image](https://github.com/elementary/installer/assets/80143868/82711101-3117-46a6-ba15-ed9977ba3bce)

**Comment by danirabbit** [comment]
Yeah I'm sure they're getting this icon from the same place :) It's probably an Ubuntu branding package or something

**Comment by danirabbit** [comment]
Fixed now that base files is patched :)
