### ISSUE TITLE
Only the languages I select in the installation process should be installed after all

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/installer#755]
### What Happened?

I selected exactly one language for installation in the installation process.
After a fresh installation, I count a full twenty-four installed languages under "Language & Region".

### Steps to Reproduce

1.Install a fresh system and select the system language "English".
2.Check the "Language & Region" plugin after installation.

### Expected Behavior

Only the languages I select in the installation process should be installed after all.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Closing for the reasoning above. None of our packages use separate lang packs
