### ISSUE TITLE
Installer is not localized

### ISSUE THREAD

**Issue by ryonakano** [elementary/installer#775]
### What Happened?

Installer of OS 8 Early Access does not get localized like 7.1 Horus.

### Steps to Reproduce

1. Boot from Early Access (I used `elementaryos-8.0-daily.20240525.iso`)
2. Wait until the installer is shown
3. See the languages list is not localized

![image 5](https://github.com/elementary/installer/assets/26003928/f2289ac4-49b0-4a76-b63b-5908892e30b9)

4. Select some language other than English
5. See the Installer UI is not localized after navigating to keyboard layout selection page

![image4](https://github.com/elementary/installer/assets/26003928/589186ec-e517-4284-9f24-0d01a9402bc0)

### Expected Behavior

1. In the step 3, the languages list should be localized like Horus:

![image6](https://github.com/elementary/installer/assets/26003928/e9a31f4d-d84d-4abd-9dc8-7525cfd754f2)

2. In the step 5, the Installer UI should be localized like Horus:

![image3](https://github.com/elementary/installer/assets/26003928/af7a3692-c111-4964-a82b-f601e12ac405)

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
Unfortunately this does not seem to be fixed in `elementaryos-8.0-daily.20240604.iso`

**Comment by danirabbit** [comment]
@ryonakano can you still reproduce this? It seems fixed for me in the latest daily

**Comment by danirabbit** [comment]
Oddly, if you log in to the demo session and then log out the installer is localized. So this must be some kind of race? The installer is being launched before localization support is loaded somehow?
