### ISSUE TITLE
Clicking a partition in the custom install glitches the installer window

### ISSUE THREAD

**Issue by ryonakano** [elementary/installer#793]
### What Happened?

Clicking a partition in the custom install glitches the installer window, which makes me being unable to set up partitions.

### Steps to Reproduce

1. Boot from Early Access 8 ISO (I used `elementaryos-8.0-daily.20240824.iso`)
2. Select the custom install
3. In the "Select Partitions" view, click "Modify Partitions…" to create partitions if none exists
4. In the "Select Partitions" view, click the storage bar (the yellow/green portion in the following screenshot)  
![VirtualBox_test_25_08_2024_10_52_43](https://github.com/user-attachments/assets/154a3849-fe8b-48a3-bc93-fb396f8c9af6)
5. See the installer window get bigger and unable to setup partitions  
![VirtualBox_test_25_08_2024_10_54_19](https://github.com/user-attachments/assets/d6cbd548-3471-459d-8633-98a8567eee02)

### Expected Behavior

The window should not glitch and the following popover should be shown where we can setup partitions:

![VirtualBox_test_25_08_2024_10_57_47](https://github.com/user-attachments/assets/9dcc125a-b4a7-4bfb-bfcc-ae25816f0dfc)

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Aug 25 02:09:05 elementary io.elementary.g[1858]: Can't update stage views actor unnamed [MetaWindowActorX11] is on because it needs an allocation.
Aug 25 02:09:05 elementary io.elementary.g[1858]: Can't update stage views actor unnamed [MetaSurfaceActorX11] is on because it needs an allocation.
Aug 25 02:09:05 elementary io.elementary.i[2053]: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed
Aug 25 02:09:05 elementary io.elementary.i[2053]: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed
Aug 25 02:09:05 elementary io.elementary.i[2053]: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed
Aug 25 02:09:05 elementary io.elementary.i[2053]: gtk_widget_size_allocate(): attempt to allocate GtkPopoverContent contents 0x562c36a38a20 with width 253 and height -23
Aug 25 02:09:05 elementary io.elementary.i[2053]: gtk_widget_size_allocate(): attempt to allocate GtkGrid grid 0x562c364c6b80 with width -2 and height -8
Aug 25 02:09:05 elementary io.elementary.installer.desktop[2053]: *** BUG ***
Aug 25 02:09:05 elementary io.elementary.installer.desktop[2053]: In pixman_region32_init_rect: Invalid rectangle passed
Aug 25 02:09:05 elementary io.elementary.installer.desktop[2053]: Set a breakpoint on '_pixman_log_error' to debug
```

[installer-glitch.log](https://github.com/user-attachments/files/16738721/installer-glitch.log)

**Comment by vjr** [comment]
I've also seen this sizing glitch happen at other stages/steps/choices of the installer, especially toward the end when it completes install and you are supposed to click the shutdown/reboot button.

**Comment by danirabbit** [comment]
This only affects the Gtk4 port, before 8.0 was released so doesn't actually affect OS 8 release currently. But will need to be fixed before another installer release

**Comment by dar5hak** [comment]
Saw this on dailies too, but doesn't reproduce in RC.

**Comment by teamcons** [comment]
On elementaryos-8.0-stable.20240918rc, it did not happen.

However once everything was installed, the last page of the installer did glitch into infinite large on the right.

> I've also seen this sizing glitch happen at other stages/steps/choices of the installer, especially toward the end when it completes install and you are supposed to click the shutdown/reboot button.

pretty much this

**Comment by danirabbit** [comment]
Folks please read other comments before commenting. This doesn't affect the released version of installer that's in the RC. This only affects daily because it's in the GTK port
