### ISSUE TITLE
Installer doesn't launch from Applications menu in Circe daily

### ISSUE THREAD

**Issue by dar5hak** [elementary/installer#806]
### What Happened?

On a live USB boot of OS 8 daily, selecting the installer option from Applications menu does nothing.

But launching `io.elementary.installer` from CLI does launch it, albeit from the very start (until later running into #793).

### Steps to Reproduce

1. Boot up the daily from a USB.
2. Try demo mode. 
3. Open Applications menu
4. Click on installer.

Nothing happens.

### Expected Behavior

It launches and starts asking stuff.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Ye olde Dell Vostro 2520 with i5 gen 3

**Comment by dar5hak** [comment]
(Sorry, IDK how I landed on the other repo from the Android app.)

**Comment by danirabbit** [comment]
The installer desktop file just runs [`gnome-session-quit --logout`](https://github.com/elementary/installer/blob/main/data/io.elementary.installer.desktop.in)

If that's for some reason not working anymore, I suppose we could call dbus directly? like `dbus-send --session --dest=org.gnome.SessionManager --print-reply /org/gnome/SessionManager org.gnome.SessionManager.Logout int32:0`

**Comment by dar5hak** [comment]
Wait, if it simply logs you out, does it mean we no longer support using the desktop while installation is in progress? (Not a feature request; just asking.)

**Comment by danirabbit** [comment]
@dar5hak Yeah since like 3 years https://github.com/elementary/installer/pull/553

**Comment by dar5hak** [comment]
Reproduced this on RC.

**Comment by teamcons** [comment]
Still present in RC as well. Left me confused for a few minutes until i checked the .desktop file

**Comment by ryonakano** [comment]
Reopening since https://github.com/elementary/installer/pull/819#issuecomment-2386186253
