### ISSUE TITLE
Error view

### ISSUE THREAD

**Issue by cassidyjames** [elementary/installer#81]
I know @jackpot51's code is 👌 but in case something goes wrong and the installation can't proceed, we should have an error view designed. Probably just similar to the success view.

**Comment by cassidyjames** [comment]
Potential copy 

# Could not install _OS_

The installation failed, so your device may not restart properly. You can try one of the following:

- Try the installation again
- Launch a session and try to manually recover
- Restart your device to boot from another drive

\> Technical details

`Restart Device` `Launch Session` `Try Installing Again`

**Comment by danrabbit** [comment]
Closed by #105
